
# SEO settings
title: "Jiaming"
title2: "space" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://garminwu.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/garminwu/garminwu.github.io/
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Wu Jiaming"
  job      : "student from HLJu"
  bio      : "Every little helps."
  thumb    : /images/author.jpg
  email    : garminwu@126.com
  url      : http://garminwu.github.io
  github   : http://github.com/garminwu


# social settings
og_locale: "en_US"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
